default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: rails-api-db-1

development:
  <<: *default
  database: jibun_log_development

test:
  <<: *default
  database: jibun_log_test

production:
  <<: *default
  database: jibun_log_production
  username: <%= ENV['MYAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
